project_id = "cnzgnsodowyccuyzaayx"

[functions.real-multi-llm]
verify_jwt = false

[functions.wisdomnet-chat]
verify_jwt = false

[functions.gemini-agents]
verify_jwt = false

[functions.google-ai-orchestrator]
verify_jwt = false

[functions.document-processor]
verify_jwt = false

[functions.document-ai-editor]
verify_jwt = true

[functions.cmc-chat]
verify_jwt = false